import os
import json
import sys
import importlib.util
from typing import Dict, Optional
from dotenv import load_dotenv
import google.generativeai as genai

load_dotenv()


class GeminiService:
    """Service for AI analysis using Google Gemini API"""
    
    def __init__(self):
        """Initialize Gemini service with API key"""
        api_key = os.getenv('GEMINI_API_KEY')
        self.model = None
        self.initialized = False
        
        # If not in environment, try to load from local_values.py in new-ui folder
        if not api_key:
            try:
                # Get the path to new-ui/local_values.py
                backend_dir = os.path.dirname(os.path.abspath(__file__))
                project_root = os.path.dirname(backend_dir)
                local_values_path = os.path.join(project_root, 'new-ui', 'local_values.py')
                
                print(f"[GEMINI] Attempting to load API key from: {local_values_path}")
                
                if os.path.exists(local_values_path):
                    # Load the module dynamically
                    spec = importlib.util.spec_from_file_location("local_values", local_values_path)
                    local_values_module = importlib.util.module_from_spec(spec)
                    spec.loader.exec_module(local_values_module)
                    
                    if hasattr(local_values_module, 'GEMINI_API_KEY'):
                        api_key = local_values_module.GEMINI_API_KEY
                        print(f"[GEMINI] Successfully loaded API key from {local_values_path}")
                    else:
                        print(f"[GEMINI] GEMINI_API_KEY not found in {local_values_path}")
                else:
                    print(f"[GEMINI] File not found: {local_values_path}")
            except Exception as e:
                print(f"[GEMINI] Error loading from local_values.py: {e}")
                import traceback
                traceback.print_exc()
        
        if not api_key:
            print("[WARNING] Gemini service not initialized: GEMINI_API_KEY not found in environment variables or local_values.py")
            return
        
        try:
            print(f"[GEMINI] Configuring Gemini with API key (length: {len(api_key)})")
            genai.configure(api_key=api_key)
            self.model = genai.GenerativeModel('gemini-2.5-flash')
            self.initialized = True
            print(f"[GEMINI] Service initialized successfully")
        except Exception as e:
            print(f"[WARNING] Failed to initialize Gemini service: {e}")
    
    def generate_analysis(self, kundli_data: Dict, user_name: str, analysis_type: str = 'comprehensive') -> str:
        """
        Generate AI analysis for kundli using Gemini API
        
        Args:
            kundli_data: Dictionary with kundli information
            user_name: Name of the person
            analysis_type: Type of analysis (comprehensive, career, relationships, health, etc.)
            
        Returns:
            Analysis text generated by Gemini
        """
        if not self.initialized or not self.model:
            raise Exception("Gemini service not initialized. Please set GEMINI_API_KEY environment variable.")
        
        try:
            prompt = self._build_analysis_prompt(kundli_data, user_name, analysis_type)
            
            response = self.model.generate_content(prompt)
            
            if response.text:
                return response.text
            else:
                return f"Unable to generate analysis. Please try again."
        
        except Exception as e:
            raise Exception(f"Failed to generate analysis with Gemini: {str(e)}")
    
    def generate_response(self, prompt: str) -> str:
        """
        Generate a response from Gemini for a given prompt
        
        Args:
            prompt: The prompt to send to Gemini
            
        Returns:
            Response text from Gemini
        """
        if not self.initialized or not self.model:
            raise Exception("Gemini service not initialized. Please set GEMINI_API_KEY environment variable.")
        
        try:
            response = self.model.generate_content(prompt)
            
            if response.text:
                return response.text
            else:
                return "Unable to generate response. Please try again."
        
        except Exception as e:
            raise Exception(f"Failed to generate response with Gemini: {str(e)}")
    
    def _build_analysis_prompt(self, kundli_data: Dict, user_name: str, analysis_type: str) -> str:
        """
        Build a detailed prompt for Gemini based on kundli data
        
        Args:
            kundli_data: Kundli data dictionary
            user_name: Name of the person
            analysis_type: Type of analysis requested
            
        Returns:
            Formatted prompt for Gemini
        """
        prompt = f"""You are an expert Vedic astrologer. Provide a detailed {analysis_type} astrological analysis for {user_name} based on the following kundli (birth chart) data:

Kundli Data:
{json.dumps(kundli_data, indent=2, default=str)}

Please provide:
1. A comprehensive overview of the person's astrological profile
2. Key planetary positions and their significance
3. House placements and their implications
4. Yogas (auspicious combinations) if present
5. Challenges and remedies
6. Life predictions and guidance

Format the response in a clear, readable manner with proper sections and headings. Be specific and insightful based on the actual kundli data provided.

IMPORTANT: At the end of your analysis, add a section titled "KEY INSIGHTS" with 5-10 specific, actionable insights covering:
- Health outlook for next 3 months (what to be careful about)
- 2 career-related insights
- Marriage, relationships, and family insights
- Money, wealth, and business insights

Each insight should be 1-2 sentences, specific to the kundli data, and actionable."""
        
        return prompt
